apiVersion: v1
kind: Pod
metadata:
  name: metasploit
  labels:
    app: metasploit
spec:
  containers:
  - name: metasploit
    image: msepehr/metasploit:v0.2
    command: ['sh', '-c', 'echo The Pod is running && sleep 6000']

